In [1]:
from IPython.display import display, Markdown, Latex
from fractions import Fraction
import pandas as pd


def getResistances(switchPositions, res0, res1, res2, res4, res8):
    def getResistance(switchPos):
        res = res0
        if switchPos & 0x01: res += res1
        if switchPos & 0x02: res += res2
        if switchPos & 0x04: res += res4
        if switchPos & 0x08: res += res8
        return res
    return [getResistance(switchPos) for switchPos in range(switchPositions)]


def calculate(title, r1, switchPositions, res0, res1, res2, res4, res8):
    r2Resistances = getResistances(switchPositions, res0, res1, res2, res4, res8)
    r2MidPoint = int((max(r2Resistances) + min(r2Resistances)) / 2)
    ratios = list(map(lambda r2: Fraction(r2, r1), r2Resistances))

    #tableData = \
    #    '| Switch position | R2 resistance | R2 / R1 ratio |\n' + \
    #    '| --------------- | ------------- | ------------- |\n' + \
    #    '\n'.join(['| {} | {} | {} |'.format(i, r2Resistances[i], ratios[i]) for i in range(switchPositions)])

    markdownStr = '''
    # {0}
    * R1 resistance = {1}
    * R2 mid point = {2}
    '''.strip().format(title, r1, r2MidPoint)
    display(Markdown(markdownStr))

    data = [[i, r2Resistances[i], '{} / {}'.format(r2Resistances[i], r1), ratios[i]] for i in range(switchPositions)]
    columns=['Switch position', 'R2 resistance', 'R2 / R1', 'R2 / R1 ratio']
    display(pd.DataFrame(data, columns=columns))

In [2]:
calculate('Standard loadout - 10 position switch', 5000, 10, 1000, 1000, 2000, 4000, 8000)

# Standard loadout - 10 position switch
    * R1 resistance = 5000
    * R2 mid point = 5500

   Switch position  R2 resistance       R2 / R1 R2 / R1 ratio
0                0           1000   1000 / 5000           1/5
1                1           2000   2000 / 5000           2/5
2                2           3000   3000 / 5000           3/5
3                3           4000   4000 / 5000           4/5
4                4           5000   5000 / 5000             1
5                5           6000   6000 / 5000           6/5
6                6           7000   7000 / 5000           7/5
7                7           8000   8000 / 5000           8/5
8                8           9000   9000 / 5000           9/5
9                9          10000  10000 / 5000             2

In [3]:
calculate('Standard loadout - 16 position switch', 5000, 16, 1000, 1000, 2000, 4000, 8000)

# Standard loadout - 16 position switch
    * R1 resistance = 5000
    * R2 mid point = 8500

    Switch position  R2 resistance       R2 / R1 R2 / R1 ratio
0                 0           1000   1000 / 5000           1/5
1                 1           2000   2000 / 5000           2/5
2                 2           3000   3000 / 5000           3/5
3                 3           4000   4000 / 5000           4/5
4                 4           5000   5000 / 5000             1
5                 5           6000   6000 / 5000           6/5
6                 6           7000   7000 / 5000           7/5
7                 7           8000   8000 / 5000           8/5
8                 8           9000   9000 / 5000           9/5
9                 9          10000  10000 / 5000             2
10               10          11000  11000 / 5000          11/5
11               11          12000  12000 / 5000          12/5
12               12          13000  13000 / 5000          13/5
13               13          14000  14000 / 5000          14/5
14               14          15000  15000 / 5000             3
15               15          16000  16000 / 5000          16/5